# SPDX-License-Identifier: GPL-2.0-or-later
# ParityQC © 2026. See LICENSE.txt in the top level directory for details.
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        update-types: ['minor', 'patch']

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
